import { Peer } from 'peerjs';
import type { DataConnection } from 'peerjs';

export interface FileMetadata {
  name: string;
  size: number;
  type: string;
}

export interface TransferStats {
  progress: number; // percentage (0 to 100)
  speed: number;    // bytes per second
  bytesTransferred: number;
  timeRemaining: number; // seconds
}

export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected-p2p' | 'connected-turn';

const CHUNK_SIZE = 64 * 1024; // 64KB chunks
const BUFFER_THRESHOLD = 1024 * 1024; // 1MB buffer threshold for backpressure

export class P2PEngine {
  private peer: Peer | null = null;
  private connection: DataConnection | null = null;


  // Callbacks for UI updates
  public onStatusChange?: (status: ConnectionStatus) => void;
  public onPeerIdReady?: (id: string) => void;
  public onMetadataReceived?: (metadata: FileMetadata) => void;
  public onProgress?: (stats: TransferStats) => void;
  public onTransferComplete?: (downloadUrl?: string) => void;
  public onError?: (error: string) => void;

  constructor() {}

  /**
   * Initializes the PeerJS client
   * @param customId Optional custom peer ID (used by receiver to connect to sender)
   */
  public initialize(customId?: string): void {
    this.cleanup();
    this.updateStatus('connecting');

    // Standard STUN/TURN servers to punch through NATs reliably
    const config = {
      iceServers: [
        { urls: 'stun:stun.l.google.com:19302' },
        { urls: 'stun:stun1.l.google.com:19302' },
        { urls: 'stun:stun2.l.google.com:19302' },
        { urls: 'stun:stun.services.mozilla.com' },
        // Public free TURN relay to punch through carrier symmetric NATs / mobile hotspots
        {
          urls: 'turn:openrelay.metered.ca:80',
          username: 'openrelay',
          credential: 'openrelay'
        },
        {
          urls: 'turn:openrelay.metered.ca:443',
          username: 'openrelay',
          credential: 'openrelay'
        },
        {
          urls: 'turn:openrelay.metered.ca:443?transport=tcp',
          username: 'openrelay',
          credential: 'openrelay'
        }
      ],
    };

    try {
      this.peer = customId ? new Peer(customId, { config }) : new Peer({ config });

      this.peer.on('open', (id) => {
        this.updateStatus('disconnected'); // Successfully registered on signaling, now idle/ready
        if (this.onPeerIdReady) {
          this.onPeerIdReady(id);
        }
      });

      this.peer.on('connection', (conn) => {
        // Only accept one connection in our prototype
        if (this.connection) {
          conn.close();
          return;
        }
        this.setupConnection(conn);
      });

      this.peer.on('error', (err) => {
        console.error('PeerJS error:', err);
        if (this.onError) {
          this.onError(err.message || 'Peer network failure.');
        }
        this.updateStatus('disconnected');
      });
    } catch (e: any) {
      if (this.onError) {
        this.onError(e.message || 'Failed to instantiate PeerJS.');
      }
      this.updateStatus('disconnected');
    }
  }

  /**
   * Connects as a receiver to the sender's peer ID
   * @param senderPeerId The short code generated by the sender
   */
  public connectToPeer(senderPeerId: string): void {
    const doConnect = () => {
      this.updateStatus('connecting');
      try {
        const conn = this.peer!.connect(senderPeerId, {
          reliable: true,
        });
        this.setupConnection(conn);
      } catch (err: any) {
        if (this.onError) {
          this.onError(err.message || 'Failed to initiate P2P channel.');
        }
        this.updateStatus('disconnected');
      }
    };

    if (!this.peer) {
      this.initialize();
    }

    if (this.peer!.open) {
      doConnect();
    } else {
      this.updateStatus('connecting');
      this.peer!.once('open', () => {
        doConnect();
      });
      this.peer!.once('error', (err) => {
        if (this.onError) {
          this.onError('Could not connect to signaling server: ' + err.message);
        }
        this.updateStatus('disconnected');
      });
    }
  }

  /**
   * Sends a file to the connected peer
   * @param file The file object from input or dropzone
   */
  public async sendFile(file: File): Promise<void> {
    if (!this.connection) {
      throw new Error('No active peer connection');
    }

    const metadata: FileMetadata = {
      name: file.name,
      size: file.size,
      type: file.type || 'application/octet-stream',
    };

    // 1. Send file metadata
    this.connection.send({ type: 'metadata', data: metadata });

    // 2. Start chunked file transmission
    const fileReader = new FileReader();
    let offset = 0;
    const totalSize = file.size;
    let chunkIndex = 0;
    
    let startTime = Date.now();
    let lastStatsTime = Date.now();

    const dataChannel = (this.connection as any).dataChannel as RTCDataChannel;

    const readNextChunk = () => {
      const slice = file.slice(offset, offset + CHUNK_SIZE);
      fileReader.readAsArrayBuffer(slice);
    };

    fileReader.onload = async (e) => {
      if (e.target?.result instanceof ArrayBuffer) {
        const buffer = e.target.result;

        // Apply backpressure using RTCDataChannel's bufferedAmount
        if (dataChannel && dataChannel.bufferedAmount > BUFFER_THRESHOLD) {
          await this.waitBufferLow(dataChannel);
        }

        // Send the raw binary chunk directly
        if (this.connection && this.connection.open) {
          this.connection.send(buffer);

          offset += buffer.byteLength;
          chunkIndex++;

          // Real-time speed metrics calculation
          const now = Date.now();
          if (now - lastStatsTime >= 200 || offset === totalSize) {
            const timePassed = (now - startTime) / 1000;
            const currentSpeed = offset / timePassed; // bytes/sec
            const remainingBytes = totalSize - offset;
            const timeRemaining = remainingBytes / (currentSpeed || 1);

            if (this.onProgress) {
              this.onProgress({
                progress: Math.min((offset / totalSize) * 100, 100),
                speed: currentSpeed,
                bytesTransferred: offset,
                timeRemaining: Math.max(0, Math.round(timeRemaining)),
              });
            }
            lastStatsTime = now;
          }

          if (offset < totalSize) {
            readNextChunk();
          } else {
            // Signal completed transfer
            this.connection.send({ type: 'done' });
            if (this.onTransferComplete) {
              this.onTransferComplete();
            }
          }
        }
      }
    };

    fileReader.onerror = () => {
      if (this.onError) {
        this.onError('Error reading file chunk.');
      }
    };

    // Initiate first chunk read
    readNextChunk();
  }

  /**
   * Helper to wait until the WebRTC buffer is low enough to prevent browser memory blowout
   */
  private waitBufferLow(dataChannel: RTCDataChannel): Promise<void> {
    return new Promise((resolve) => {
      const checkBuffer = () => {
        if (dataChannel.bufferedAmount < BUFFER_THRESHOLD) {
          resolve();
        } else {
          setTimeout(checkBuffer, 20);
        }
      };
      
      if ('onbufferedamountlow' in dataChannel) {
        const onLow = () => {
          dataChannel.removeEventListener('bufferedamountlow', onLow);
          resolve();
        };
        dataChannel.addEventListener('bufferedamountlow', onLow);
      } else {
        checkBuffer();
      }
    });
  }

  /**
   * Configures data connection listeners
   */
  private setupConnection(conn: DataConnection): void {
    this.connection = conn;

    conn.on('open', () => {
      // Determine if we are running in P2P or TURN relay mode
      let pc: RTCPeerConnection | null = null;
      try {
        const peerInstance = this.peer as any;
        const conns = peerInstance._connections?.[conn.peer] || peerInstance.connections?.[conn.peer];
        if (Array.isArray(conns) && conns[0]) {
          pc = conns[0].peerConnection;
        }
      } catch (e) {
        console.error('Failed to extract PeerConnection:', e);
      }

      if (pc) {
        // Fallback detection based on ICE candidate type
        this.detectIceCandidateType(pc);
      } else {
        this.updateStatus('connected-p2p');
      }
    });

    let receivedMetadata: FileMetadata | null = null;
    let receivedChunks: any[] = [];
    let bytesReceived = 0;
    let startTime = Date.now();
    let lastStatsTime = Date.now();

    conn.on('data', (payload: any) => {
      if (!payload) return;

      // Detect binary chunks (ArrayBuffer or typed array views)
      let isChunk = false;
      let chunkBuffer: any = null;

      if (payload instanceof ArrayBuffer) {
        isChunk = true;
        chunkBuffer = payload;
      } else if (payload instanceof Uint8Array) {
        isChunk = true;
        chunkBuffer = payload.buffer;
      } else if (payload && payload.buffer instanceof ArrayBuffer) {
        isChunk = true;
        chunkBuffer = payload.buffer;
      }

      if (isChunk && chunkBuffer && receivedMetadata) {
        receivedChunks.push(chunkBuffer);
        bytesReceived += chunkBuffer.byteLength;

        const now = Date.now();
        if (now - lastStatsTime >= 200 || bytesReceived === receivedMetadata.size) {
          const timePassed = (now - startTime) / 1000;
          const currentSpeed = bytesReceived / timePassed;
          const remainingBytes = receivedMetadata.size - bytesReceived;
          const timeRemaining = remainingBytes / (currentSpeed || 1);

          if (this.onProgress) {
            this.onProgress({
              progress: Math.min((bytesReceived / receivedMetadata.size) * 100, 100),
              speed: currentSpeed,
              bytesTransferred: bytesReceived,
              timeRemaining: Math.max(0, Math.round(timeRemaining)),
            });
          }
          lastStatsTime = now;
        }
        return;
      }

      // Handle control messages
      if (typeof payload === 'object' && payload.type) {
        switch (payload.type) {
          case 'metadata':
            receivedMetadata = payload.data as FileMetadata;
            receivedChunks = [];
            bytesReceived = 0;
            startTime = Date.now();
            lastStatsTime = Date.now();
            if (this.onMetadataReceived) {
              this.onMetadataReceived(receivedMetadata);
            }
            break;

          case 'done':
            if (receivedMetadata && receivedChunks.length > 0) {
              // Reassemble the incoming file chunks into a single Blob
              const fileBlob = new Blob(receivedChunks, { type: receivedMetadata.type });
              const downloadUrl = URL.createObjectURL(fileBlob);
              if (this.onTransferComplete) {
                this.onTransferComplete(downloadUrl);
              }
              // Clean up buffer
              receivedChunks = [];
            }
            break;
        }
      }
    });

    conn.on('close', () => {
      this.updateStatus('disconnected');
      this.connection = null;
    });

    conn.on('error', (err) => {
      console.error('Connection error:', err);
      if (this.onError) {
        this.onError('P2P connection experienced a handshake issue.');
      }
      this.updateStatus('disconnected');
    });
  }

  /**
   * Analyzes RTCPeerConnection to check if direct P2P or TURN relay is used
   */
  private async detectIceCandidateType(pc: RTCPeerConnection): Promise<void> {
    try {
      const stats = await pc.getStats();
      let activeCandidatePairId = '';
      
      stats.forEach((report) => {
        if (report.type === 'transport' && report.selectedCandidatePairId) {
          activeCandidatePairId = report.selectedCandidatePairId;
        }
      });

      let isRelay = false;
      if (activeCandidatePairId) {
        const candidatePair = stats.get(activeCandidatePairId);
        if (candidatePair && candidatePair.remoteCandidateId) {
          const remoteCandidate = stats.get(candidatePair.remoteCandidateId);
          if (remoteCandidate && remoteCandidate.candidateType === 'relay') {
            isRelay = true;
          }
        }
      }

      this.updateStatus(isRelay ? 'connected-turn' : 'connected-p2p');
    } catch {
      this.updateStatus('connected-p2p');
    }
  }

  /**
   * Disconnects and cleans up all active peer allocations
   */
  public cleanup(): void {
    if (this.connection) {
      this.connection.close();
      this.connection = null;
    }
    if (this.peer) {
      this.peer.destroy();
      this.peer = null;
    }
    this.updateStatus('disconnected');
  }

  private updateStatus(status: ConnectionStatus): void {
    if (this.onStatusChange) {
      this.onStatusChange(status);
    }
  }
}
